"""third migrate

Revision ID: 09db9dbd8254
Revises: c69e163bd18f
Create Date: 2022-05-16 13:42:24.160333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09db9dbd8254'
down_revision = 'c69e163bd18f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('blogs_author_fkey', 'blogs', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('blogs_author_fkey', 'blogs', 'users', ['author'], ['id'])
    # ### end Alembic commands ###
